project:
  type: website
  output-dir: docs

website:
  title: "Dwayne Tucker"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - education.qmd
      - projects.qmd
      - awards.qmd
      - publications.qmd
      

format:
  html:
    theme: sandstone
    fontsize: 1rem
    css: styles.css
    toc: true
    toc-depth: 6



