project:
  type: website
  output-dir: docs

website:
  title: "Dwayne R. Tucker, PhD Candidate"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - awards.qmd

format:
  html:
    theme: solar
    css: styles.css
    toc: true



