project:
  type: website
  output-dir: docs

website:
  title: "Dwayne Tucker"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - skills.qmd
      - projects.qmd
      - publications.qmd
      - awards.qmd
      - RShiny.qmd


      
format:
  html:
    theme: 
      light: Spacelab
      dark: Superhero
    fontsize: 1rem
    css: styles.css
    toc: true
    toc-depth: 6

