---
title: "Awards, Honours and Grants"
---

*	Best Oral Communication at the 10th SEUD Congress in Geneva, Switzerland (2024) - Society for Endometriosis & Uterine Disorder; 500 euros (~740 CAD)
*	SEUD International Travel Award (2024) – Society for Endometriosis & Uterine Disorder; 1000 euros (~ 1470 CAD)
*	Faculty of Medicine Travel Award (2024) – U.B.C.; 500 CAD
*	Shaughnessy hospital Society Fellowship in Health Care (2022-2023) - U.B.C.; 8350 CAD	
*	Michael Smith Memorial Fellowship (2022-2023) - U.B.C.; 4275 CAD	
*	Anti-racism Initiative Grant winner (2021) – U.B.C. Anti-Racism Initiatives Fund (5000 CAD) + Graduate Postdoctoral Studies (6000 CAD)
*	Top Three Oral Presentation (2021) – CanSAGE Conference, Canada 
*	BC Women’s Health Research Institute Graduate Research award in Women’s Health (2021-2022); CAD 13,500
*	Graduate Student Travel Award (2022) – U.B.C.; 500 CAD
*	The Presidents Academic Excellence Initiative PhD award (2020-2024) – U.B.C.; 6000 CAD 
*	Faculty of Medicine Graduate Awards (2019-2023) – U.B.C.; 8,000 CAD
*	International Tuition Awards (2016-2023) – U.B.C.; 16,000 CAD 
*	Declined: Developing Solution Scholarship (2016-2017) – The University of Nottingham (U.K.); £19,300 (~ 32500 CAD)
*	Outstanding Service Award to Clinical Chemistry between 2010 and 2019 (2019); University of the West Indies, Jamaica
*	Special Alumni Award (2019); York Castle High School, Jamaica
*	University of Nottingham’s Partnership scholarship award (U.K.) (2016-2017); £19,300  (~ 32500 CAD)	
* First Caribbean native to receive this award
*	British Chevening Scholarship (2016-2017)- Foreign & Commonwealth Office (U.K.); £34,500	(~58,100CAD)	*First Jamaican to receive this award from the biomedical field
*	Most Outstanding Intern on Rotation (2010) – University Hospital of the West Indies
*	University Honour Roll (2002- 2010) - Northern Caribbean University, Jamaica (entire tenure) 
