---
title: "Publications"
page-layout: full
---
### Journal Articles

* **Tucker DR**, Dungate B, Chiu DS, Noga HL, Lee C, Bedaiwy MA, Williams C, Allaire C, Talhouk A, Yong PJ et al. Endometriosis Pain Index: Development of models to predict poor pain-related quality of life after endometriosis surgery through machine learning analysis of registry data. PAIN. 2025

* Cheng V, Amiri N, Cheng V, Ellis U, Cragg JJ, Proulx L, **Tucker DR**, & De VeraMA.[Scoping review of biosimilar disease-modifying antirheumatic drugs in pregnancy: evidence gaps and proposed outcome reporting framework](https//https://pubmed.ncbi.nlm.nih.gov/41021022/). Rheumatology international. 2025.

* **Tucker DR**, Lee AF, Orr NL, Alotaibi FT, Noga HL, Williams C, Allaire C, Bedaiwy MA, Huntsman DG, Köbel M, Anglesio MA, Yong PJ. [Somatic PTEN and ARID1A loss and endometriosis disease burden: a longitudinal study](https://academic.oup.com/humrep/advance-article/doi/10.1093/humrep/deae269/7928994). Human Reproduction. 2024

* Sreya M, **Tucker DR**, Yi J, Alotaibi FT, Lee AF, Noga H, Yong PJ.[Nerve Bundle Density and Expression of NGF and IL-1β Are Intra-Individually Heterogenous in Subtypes of Endometriosis](https://www.mdpi.com/2218-273X/14/5/583). Biomolecules. 2024.

* Dungate B, **Tucker DR**, Goodwin E, Yong PJ. <a href="https://pubmed.ncbi.nlm.nih.gov/38686828"> Assessing the Utility of artificial intelligence in endometriosis: Promises and pitfalls. </a> Womens Health (Lond). 2024.

* Zoet G, **Tucker DR**, Orr NL, Alotaibi FT, Liu YD, Noga H, Köbel M, Yong PJ. <a href="https://pubmed.ncbi.nlm.nih.gov/38098984"> Standardized protocol for quantification of nerve bundle density as a biomarker for endometriosis. </a> Front Reprod Health. 2023.

* **Tucker DR**, Noga HL, Lee C, Chiu DS, Bedaiwy MA, Williams C, Allaire C, Talhouk A, Yong PJ. <a href="https://pubmed.ncbi.nlm.nih.gov/37148956"> Pelvic pain comorbidities associated with quality of life after endometriosis surgery. </a> Am J Obstet Gynecol. 2023. 

* **Tucker D**, Zheng W, Zhang DH, Dong X. <a href="https://pubmed.ncbi.nlm.nih.gov/32879844"> Circular RNA and its potential as prostate cancer biomarkers. </a> World J Clin Oncol. 2020.

* Donovan McGrowder, **Dwayne Tucker**, Fabian Miller. <a href="https://www.worldwidejournals.com/indian-journal-of-applied-research-(IJAR)/article/prostate-specific-antigen-testing-in-a-tertiary-teaching-hospital/MTcyMDQ=/?is=1&b1=121&k=31"> Prostate Specific Antigen Testing in a Tertiary Teaching Hospital. </a> Indian Journal of Applied Research. 2019.


### Book Chapters
* Miller, F., Anderson, M., **Tucker, D.**, Vaz, K., Brown, J., Anderson-Jackson, L., & McGrowder, D. A. <a href="https://www.igi-global.com/chapter/diabetes/252423">  Diabetes: biopsychosocial features affecting metabolic control and treatment adherence. </a> Biopsychosocial Perspectives and Practices for Addressing Communicable and Non-Communicable Diseases, edited by Simon George Taukeni, 106-133. Hershey, PA: IGI Global, 2020.

* Anderson, M., **Tucker, D.**, Miller, F. G., Vaz, K., Anderson-Jackson, L., & McGrowder, D. <a href="https://www.igi-global.com/chapter/quality-of-life-and-well-being-of-breast-cancer-patients/248708"> Quality of Life and Well-Being of Breast Cancer Patients. </a> In Psycho-Social Perspectives on Mental Health and Well-Being, edited by Srinivasan Padmanaban and Chittaranjan Subudhi, 67-94. Hershey, PA: IGI Global, 2020. 

* McGrowder, D., **Tucker, D.**, Miller, F. G., Anderson, M., Vaz, K. A., & Anderson-Jackson, L. <a href= "https://www.igi-global.com/chapter/accreditation-of-medical-laboratories/258798"> Accreditation of Medical Laboratories: Challenges and Opportunities. </a> Handbook of Research on Modern Educational Technologies, Applications, and Management, edited by Mehdi Khosrow-Pour D.B.A., 600-616. Hershey, PA: IGI Global, 2021. 

*   **Tucker D**, Anderson M, Miller F, Vaz K, Anderson-Jackson L, McGrowder D. <a href="https://www.intechopen.com/chapters/66809"> Dietary Antioxidants in the Chemoprevention of Prostate Cancer [Internet]. Antioxidants. </a> IntechOpen; 2019.

